name: Maintain Collection

on:
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

# Permissions needed to push to main
permissions:
  contents: write

jobs:
  maintain-collection:
    runs-on: ubuntu-latest
    # Skip this workflow if the push was made by the GitHub Actions bot
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Need to fetch with depth=0 to properly push back
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Alphabetize resources
        run: |
          python -c "
          import yaml
          with open('collection.yaml', 'r') as f:
              data = yaml.safe_load(f)
          data['00000016']['resources'].sort()
          with open('collection.yaml', 'w') as f:
              yaml.dump(data, f, default_flow_style=False)
          "

      - name: Generate bioregistry rules
        run: python generate_bioregistry_rules.py

      - name: Check if changes exist
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in the repository"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in the repository"
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git add collection.yaml bioregistry.ts
          git commit -m "Automated: Alphabetize resources and update bioregistry.ts"
          git push origin HEAD:main 