name: Maintain Collection

on:
  push:
    branches:
      - main

jobs:
  maintain-collection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Generate bioregistry rules
        run: python generate_bioregistry_rules.py

      - name: Alphabetize resources
        run: |
          python -c "
          import yaml
          with open('collection.yaml', 'r') as f:
              data = yaml.safe_load(f)
          data['00000016']['resources'].sort()
          with open('collection.yaml', 'w') as f:
              yaml.dump(data, f, default_flow_style=False)
          "

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Automated: Alphabetize resources and update bioregistry.ts"
          branch: auto/maintain-collection
          title: "Automated: Alphabetize resources and update bioregistry.ts"
          body: |
            This PR was automatically generated by the maintenance workflow.
            - Alphabetizes the resources in collection.yaml
            - Updates bioregistry.ts with the latest link rules
          labels: automated, maintenance 