name: Validate Bioregistry Rules

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-rules:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BUILD_PAT }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Generate bioregistry rules
        id: generate
        run: |
          python generate_bioregistry_rules.py 2>&1 | tee validation.log
          exit ${PIPESTATUS[0]}

      - name: Check for issues
        if: failure()
        run: |
          if [ -f missing_patterns.txt ]; then
            echo "Missing patterns found for the following resources:"
            cat missing_patterns.txt
            echo "::error::Some resources are missing regex patterns. Check the logs for details."
          fi
          if [ -f duplicates.txt ]; then
            echo "Duplicate resources found:"
            cat duplicates.txt
            echo "::error::Duplicate resources found in collection.yaml. Check the logs for details."
          fi
          if [ -f invalid_prefixes.txt ]; then
            echo "Invalid prefixes found:"
            cat invalid_prefixes.txt
            echo "::error::Some prefixes are not registered in bioregistry.io. Check the logs for details."
          fi

      - name: Create Pull Request Comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let message = '## Bioregistry Collection Issues\n\n';
            let hasIssues = false;
            
            if (fs.existsSync('missing_patterns.txt')) {
              const missingPatterns = fs.readFileSync('missing_patterns.txt', 'utf8');
              message += '### Missing Regex Patterns\n\n';
              message += 'The following resources are missing regex patterns:\n\n';
              message += '```\n';
              message += missingPatterns;
              message += '\n```\n\n';
              message += 'Please check if these resources are correctly registered in bioregistry.io.\n\n';
              hasIssues = true;
            }
            
            if (fs.existsSync('duplicates.txt')) {
              const duplicates = fs.readFileSync('duplicates.txt', 'utf8');
              message += '### Duplicate Resources\n\n';
              message += 'The following resources appear multiple times in collection.yaml:\n\n';
              message += '```\n';
              message += duplicates;
              message += '\n```\n\n';
              message += 'Please remove the duplicate entries.\n\n';
              hasIssues = true;
            }

            if (fs.existsSync('invalid_prefixes.txt')) {
              const invalidPrefixes = fs.readFileSync('invalid_prefixes.txt', 'utf8');
              message += '### Invalid Prefixes\n\n';
              message += 'The following prefixes are not registered in bioregistry.io:\n\n';
              message += '```\n';
              message += invalidPrefixes;
              message += '\n```\n\n';
              message += 'Please check if these prefixes are correct or need to be registered.\n\n';
              hasIssues = true;
            }

            // Parse validation.log for missing resolver and deprecated resources
            if (fs.existsSync('validation.log')) {
              const log = fs.readFileSync('validation.log', 'utf8');
              
              // Extract cross-interference test results
              const interferenceMatch = log.match(/--- Cross-Interference Test Report ---\s+([\s\S]*?)--------------------------------------/);
              if (interferenceMatch && interferenceMatch[1]) {
                const interferenceReport = interferenceMatch[1].trim();
                if (interferenceReport && !interferenceReport.includes('No cross-interference issues detected')) {
                  message += '### Cross-Interference Test Results\n\n';
                  message += 'The following regexes have been identified as causing cross-interference and have been wrapped in non-capturing groups:\n\n';
                  message += '```\n';
                  message += interferenceReport;
                  message += '\n```\n\n';
                  hasIssues = true;
                }
              }
              
              // Extract missing resolver resources
              const missingResolverMatch = log.match(/Missing resolver for the following resources:\s+([\s\S]*?)(?=Deprecated resources detected:|$)/);
              if (missingResolverMatch && missingResolverMatch[1]) {
                const missingResolver = missingResolverMatch[1].trim().split('\n').filter(Boolean);
                if (missingResolver.length > 0) {
                  message += '### Missing Resolver\n\n';
                  message += 'The following resources do not have a resolver (uri_format) in bioregistry.io:\n\n';
                  message += '```\n';
                  message += missingResolver.join('\n');
                  message += '\n```\n\n';
                  message += 'Please check if these resources should have a resolver or be removed.\n\n';
                  hasIssues = true;
                }
              }
              
              // Extract deprecated resources
              const deprecatedMatch = log.match(/Deprecated resources detected:\s+([\s\S]*?)(?=$)/);
              if (deprecatedMatch && deprecatedMatch[1]) {
                const deprecated = deprecatedMatch[1].trim().split('\n').filter(Boolean);
                if (deprecated.length > 0) {
                  message += '### Deprecated Resources (Warning)\n\n';
                  message += 'The following resources or prefixes are marked as deprecated in bioregistry.io:\n\n';
                  message += '```\n';
                  message += deprecated.join('\n');
                  message += '\n```\n\n';
                  message += 'Please check if these resources should be removed or replaced.\n\n';
                }
              }
            }

            if (hasIssues || message !== '## Bioregistry Collection Issues\n\n') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            }

      - name: Cleanup temporary files
        if: always()
        run: |
          rm -f validation.log
