name: Update Bioregistry Collections

on:
  # Manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-collections:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML requests

      - name: Fetch upstream collections.json
        id: fetch
        run: |
          curl -s https://raw.githubusercontent.com/biopragmatics/bioregistry/main/src/bioregistry/data/collections.json -o upstream_collections.json
          echo "Successfully fetched upstream collections.json"

      - name: Convert YAML to JSON and merge with upstream
        id: convert
        run: |
          python -c "
          import yaml
          import json
          import os
          
          # Load the collection.yaml file
          with open('collection.yaml', 'r') as f:
              collection_data = yaml.safe_load(f)
          
          # Format our collection into the expected structure
          our_collection = {
              'authors': collection_data['00000016']['authors'],
              'description': collection_data['00000016']['description'],
              'identifier': collection_data['00000016']['identifier'],
              'name': collection_data['00000016']['name'],
              'resources': collection_data['00000016']['resources']
          }
          
          # Load the upstream collections.json
          with open('upstream_collections.json', 'r') as f:
              upstream_data = json.load(f)
          
          # Find and replace or add our collection
          our_id = our_collection['identifier']
          found = False
          
          for i, collection in enumerate(upstream_data['collections']):
              if collection['identifier'] == our_id:
                  upstream_data['collections'][i] = our_collection
                  found = True
                  break
          
          if not found:
              upstream_data['collections'].append(our_collection)
          
          # Write to our local collections.json file
          with open('collections.json', 'w') as f:
              json.dump(upstream_data, f, indent=2)
          
          print('Successfully merged our collection with upstream collections.json')
          "

      - name: Clean up temporary files
        run: |
          rm -f upstream_collections.json
          echo "Removed temporary upstream_collections.json file"

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit changes
        id: commit
        run: |
          git add collections.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Update collections.json with latest upstream data"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        if: steps.commit.outputs.changes_detected == 'true'
        with:
          title: "Update collections.json with latest upstream data"
          body: |
            This PR updates our local copy of collections.json with the latest upstream data and our collection.
            
            - Fetched latest collections.json from the upstream bioregistry repository
            - Added/updated our collection (ID: 0000016)
            
            This file can be used as a reference when preparing PRs to the upstream repository.
          branch: update-collections
          delete-branch: true 