name: URL Resolution Test

on:
  workflow_dispatch:

jobs:
  url-resolution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Run URL Resolution Test
        run: |
          python generate_bioregistry_rules.py --url-resolution-only 2>&1 | tee url_resolution.log

      - name: Post Results as PR Comment (if PR)
        if: github.event.pull_request
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let message = '## Bioregistry URL Resolution Test Results\n\n';
            if (fs.existsSync('url_resolution.log')) {
              const log = fs.readFileSync('url_resolution.log', 'utf8');
              const urlResolutionMatch = log.match(/--- URL Resolution Test Report ---\s+([\s\S]*?)----------------------------------/);
              if (urlResolutionMatch && urlResolutionMatch[1]) {
                const urlResolutionReport = urlResolutionMatch[1].trim();
                if (urlResolutionReport && !urlResolutionReport.includes('All example URLs resolved successfully')) {
                  message += 'The following URLs had resolution issues. This is for informational purposes only and does not block the PR:\n\n';
                  message += '```\n';
                  message += urlResolutionReport;
                  message += '\n```\n\n';
                  message += 'Note: These failures are often due to API rate limits, SSL issues, or temporary server problems and may not indicate actual issues with the CURIEs themselves.\n\n';
                } else {
                  message += 'All example URLs resolved successfully.';
                }
              } else {
                message += 'No URL resolution report found.';
              }
            } else {
              message += 'No url_resolution.log file found.';
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });

      - name: Upload URL Resolution Log as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: url_resolution_log
          path: url_resolution.log

      - name: Add to Workflow Summary (if not PR)
        if: ${{ !github.event.pull_request }}
        run: |
          echo '## Bioregistry URL Resolution Test Results' >> $GITHUB_STEP_SUMMARY
          if grep -q 'All example URLs resolved successfully' url_resolution.log; then
            echo 'All example URLs resolved successfully.' >> $GITHUB_STEP_SUMMARY
          else
            awk '/--- URL Resolution Test Report ---/, /----------------------------------/' url_resolution.log | sed '1d;$d' >> $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY
            echo 'Note: These failures are often due to API rate limits, SSL issues, or temporary server problems and may not indicate actual issues with the CURIEs themselves.' >> $GITHUB_STEP_SUMMARY
          fi 